import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BrainCircuit, CheckCircle2, FileCheck2, Gauge, RefreshCw, ShieldAlert, Sparkles, XCircle } from 'lucide-react';
import { api } from '../services/api';
import AIBadge from '../components/AIBadge';
import { useAuthRole } from '../context/AuthRoleContext';

const fieldLabel = { applicant_name:'Applicant / Owner', survey_number:'Survey / Khasra No.', land_area:'Land Area', district:'District', document_date:'Document Date' };

export default function IntelligenceCenterPage() {
  const { permissions } = useAuthRole();
  const [docs,setDocs] = useState([]); const [selected,setSelected] = useState([]); const [verification,setVerification] = useState(null);
  const [overview,setOverview] = useState(null); const [explanation,setExplanation] = useState(null); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false); const [error,setError] = useState('');

  const load = async () => { setLoading(true); setError(''); try { const [d,o] = await Promise.all([api.getDocuments(), api.getIntelligenceOverview()]); setDocs(d.data || []); setOverview(o); } catch(e){ setError(e.message); } finally { setLoading(false); } };
  useEffect(()=>{load();},[]);
  const selectedDocs = useMemo(()=>docs.filter(d=>selected.includes(d.id)),[docs,selected]);
  const toggle = id => setSelected(s => s.includes(id) ? s.filter(x=>x!==id) : s.length < 6 ? [...s,id] : s);
  const verify = async () => { if(selected.length<2) return; setBusy(true); setError(''); try { setVerification(await api.verifyDocuments(selected)); } catch(e){setError(e.message);} finally{setBusy(false);} };
  const explain = async id => { setBusy(true); setExplanation(null); try { setExplanation(await api.explainDistrictMetric(id)); } catch(e){setError(e.message);} finally{setBusy(false);} };

  return <div className="space-y-6">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4">
      <div><div className="flex items-center gap-2"><span className="text-xs font-bold uppercase tracking-wider text-blue-600">BhoomiIntel v3</span><AIBadge/></div><h1 className="text-3xl font-extrabold tracking-tight text-slate-950 mt-1">Intelligence Center</h1><p className="text-sm text-slate-500 mt-1 max-w-3xl">Cross-document verification, explainable district risk signals and early-warning intelligence in one workspace.</p></div>
      <button onClick={load} className="inline-flex items-center gap-2 px-4 py-2.5 bg-white border border-slate-200 rounded-xl text-sm font-semibold hover:border-blue-300"><RefreshCw className="w-4 h-4"/> Refresh intelligence</button>
    </div>
    {error && <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-sm">{error}</div>}

    <section className="grid grid-cols-1 xl:grid-cols-3 gap-5">
      <div className="xl:col-span-2 bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
        <div className="p-5 border-b border-slate-100 flex items-center justify-between"><div><h2 className="font-bold text-slate-900 flex items-center gap-2"><FileCheck2 className="w-5 h-5 text-blue-600"/> Cross-Document Verification</h2><p className="text-xs text-slate-500 mt-1">Select 2–6 published documents and compare extracted governance fields.</p></div><span className="text-xs font-bold px-2.5 py-1 rounded-full bg-slate-100 text-slate-600">{selected.length}/6 selected</span></div>
        <div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-3 max-h-72 overflow-y-auto">{loading ? <div className="text-sm text-slate-400">Loading repository…</div> : docs.slice(0,20).map(d=><button key={d.id} onClick={()=>toggle(d.id)} className={`text-left p-3 rounded-xl border transition ${selected.includes(d.id)?'border-blue-500 bg-blue-50':'border-slate-200 hover:border-blue-200'}`}><div className="flex items-start gap-3"><div className={`mt-0.5 w-5 h-5 rounded-md border flex items-center justify-center ${selected.includes(d.id)?'bg-blue-600 border-blue-600 text-white':'border-slate-300'}`}>{selected.includes(d.id)&&<CheckCircle2 className="w-3.5 h-3.5"/>}</div><div className="min-w-0"><div className="font-semibold text-sm text-slate-800 line-clamp-2">{d.title}</div><div className="text-[11px] text-slate-500 mt-1">{d.category} · {d.theme}</div></div></div></button>)}</div>
        <div className="px-5 pb-5"><button disabled={selected.length<2||busy} onClick={verify} className="w-full py-3 rounded-xl bg-slate-950 text-white text-sm font-bold disabled:opacity-40 hover:bg-blue-700 transition">{busy?'Analyzing evidence…':'Run verification analysis'}</button></div>
        {verification && <div className="border-t border-slate-100 p-5 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="p-4 rounded-xl bg-slate-50"><div className="text-xs text-slate-500">Verification score</div><div className="text-3xl font-black mt-1">{verification.risk_score}<span className="text-sm text-slate-400">/100</span></div></div><div className={`p-4 rounded-xl ${verification.risk_level==='HIGH'?'bg-rose-50':verification.risk_level==='MEDIUM'?'bg-amber-50':'bg-emerald-50'}`}><div className="text-xs text-slate-500">Risk level</div><div className="text-xl font-black mt-2">{verification.risk_level}</div></div></div>
          <div className="space-y-2">{verification.checks.map(c=><div key={c.field} className="p-3 rounded-xl border border-slate-200"><div className="flex items-center justify-between"><span className="text-sm font-bold">{fieldLabel[c.field]}</span>{c.status==='match'?<span className="text-emerald-600 flex items-center gap-1 text-xs font-bold"><CheckCircle2 className="w-4 h-4"/> MATCH</span>:c.status==='conflict'?<span className="text-rose-600 flex items-center gap-1 text-xs font-bold"><XCircle className="w-4 h-4"/> CONFLICT</span>:<span className="text-slate-400 text-xs font-bold">INSUFFICIENT</span>}</div><div className="mt-2 grid sm:grid-cols-2 gap-1">{c.values.map(v=><div key={v.document_id} className="text-[11px] text-slate-500 truncate"><b>{v.title}:</b> {v.value}</div>)}</div></div>)}</div>
          <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-800 flex gap-2"><ShieldAlert className="w-4 h-4 shrink-0"/>{verification.recommendation}</div>
        </div>}
      </div>

      <div className="bg-slate-950 text-white rounded-2xl p-5 shadow-sm"><div className="flex items-center gap-2"><BrainCircuit className="w-5 h-5 text-blue-300"/><h2 className="font-bold">Early Warning Engine</h2></div><p className="text-xs text-slate-400 mt-1">Analytical indicators from the district dataset.</p><div className="mt-5 space-y-3">{overview?.alerts?.slice(0,6).map((a,i)=><div key={i} className="p-3 rounded-xl bg-white/5 border border-white/10"><div className="flex items-start gap-2"><AlertTriangle className="w-4 h-4 text-amber-300 mt-0.5"/><div><div className="text-sm font-semibold">{a.district}</div><div className="text-xs text-slate-400 mt-0.5">{a.message}</div></div></div></div>)}{!overview?.alerts?.length&&!loading&&<div className="text-sm text-slate-400">No active warning signals.</div>}</div><div className="mt-5 text-[11px] text-slate-500">{overview?.methodology}</div></div>
    </section>

    <section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b border-slate-100"><h2 className="font-bold flex items-center gap-2"><Gauge className="w-5 h-5 text-indigo-600"/> Explainable District Risk</h2><p className="text-xs text-slate-500 mt-1">Click “Explain” to turn a computed signal into plain-language policy guidance.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="text-left p-3">District</th><th className="text-left p-3">Digitization</th><th className="text-left p-3">Disputes</th><th className="text-left p-3">Risk</th><th className="text-right p-3">Action</th></tr></thead><tbody>{overview?.districts?.slice(0,10).map(d=><tr key={d.id} className="border-t border-slate-100"><td className="p-3"><div className="font-semibold">{d.name}</div><div className="text-xs text-slate-400">{d.state}</div></td><td className="p-3">{d.digitization_progress_pct}%</td><td className="p-3">{Number(d.dispute_count).toLocaleString()}</td><td className="p-3"><span className={`px-2 py-1 rounded-full text-[11px] font-bold ${d.risk_level==='HIGH'?'bg-rose-100 text-rose-700':d.risk_level==='MEDIUM'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{d.risk_score} · {d.risk_level}</span></td><td className="p-3 text-right"><button disabled={!permissions.canRunSimulations||busy} onClick={()=>explain(d.id)} className="text-xs font-bold text-blue-600 hover:text-blue-800 disabled:text-slate-300">Explain with AI</button></td></tr>)}</tbody></table></div></section>

    {explanation && <section className="bg-blue-50 border border-blue-200 rounded-2xl p-5"><div className="flex items-center gap-2 font-bold text-blue-950"><Sparkles className="w-5 h-5"/> AI explanation · {explanation.district}</div><p className="text-sm text-blue-950/80 leading-6 mt-3 whitespace-pre-line">{explanation.explanation}</p><div className="mt-3 text-[11px] text-blue-700">{explanation.disclaimer}</div></section>}
  </div>;
}
